services:
  database:
    image: postgres:14.15-alpine3.21
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
    container_name: "postgres"
    networks:
      - backend
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    # healthcheck to make sure database is ready
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  server:
    build: server/
    environment: 
      - WEBSITE_URL=http://localhost:3000
      - DATABASE_URL=postgres://postgres:secretpassword@database:5432/postgres
    container_name: "server"
    networks:
      - backend
      - frontend
    ports:
      - "4000:4000"
    depends_on:
      database:
        condition: service_healthy
        restart: true

    restart: always

  client:
    build: client/
    environment:
      - API_URL=http://localhost:4000
    container_name: "client"
    networks:
      - frontend
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge